theme: jekyll-theme-minimal
title: GoodHabits 
description: Encourage your good habits!
email: troyan3@gmail.com
twitter_username: troyane
github_username: troyane
logo: /imgs/logo.png
show_downloads: true
# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
baseurl: /GoodHabits
